---
- name: Verify
  hosts: all
  tasks:
  - name: Check Installed a epel-release package.
    package_facts:
      manager: auto

  - name: Test if epel-release is installed.
    assert:
      that:
        - "'epel-release' in ansible_facts.packages"
